apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.externalSecrets.gcpProject}}
  dataFrom:
    - {{ .Values.externalSecrets.gcpSecretName}}